# Generated by Django 5.0.4 on 2024-12-17 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shisha", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("url", models.URLField(blank=True, null=True)),
                ("locate", models.TextField(blank=True, default="", null=True)),
                ("mood", models.TextField(blank=True, default="", null=True)),
                ("time", models.TextField(blank=True, default="", null=True)),
                ("mouth", models.BooleanField()),
                ("goods", models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="user_name",
        ),
        migrations.AddField(
            model_name="post",
            name="liked",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="like", to="shisha.user"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="shisha.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="followed_by", to="shisha.user"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="memo",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="shisha.shop",
            ),
        ),
        migrations.DeleteModel(
            name="Entry",
        ),
    ]
